version: 1
services:
  - type: web
    name: my-flask-app
    env: python
    python_version: "3.11"  # Make sure the version matches your local version
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py